"""Add ConsultationSignaling model

Revision ID: e7c555795ef4
Revises: 
Create Date: 2025-05-03 16:05:38.600258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c555795ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_signaling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('consultation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('frequency')
        batch_op.drop_column('dosage')
        batch_op.drop_column('medication')

    with op.batch_alter_table('specialty_fee_ranges', schema=None) as batch_op:
        batch_op.alter_column('recommended_fee',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialty_fee_ranges', schema=None) as batch_op:
        batch_op.alter_column('recommended_fee',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('dosage', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('consultation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('consultation_signaling')
    # ### end Alembic commands ###
